### ISSUE TITLE
change name of selection methods?

### ISSUE THREAD

**Issue by rob-vh** [wizardofzos/pyracf#36]
Currently we have .gfilter() and .rfilter(), they implement (positive) selection.  We originally decided on gfilter (generic filter) as the functionality we needed is similar to the SEARCH FILTER( ) command in TSO, and .select .match and .filter were already taken by Pandas.
Looking more closely at the built-in .filter method, it does something similar although it does not directly allow generic filters:
```
>>> r.users.filter(['ADCDA','IBMUSER'],axis=0)
 	USBD_RECORD_TYPE 	USBD_NAME 	USBD_CREATE_DATE 	USBD_OWNER_ID 	USBD_ADSP 	USBD_SPECIAL 	USBD_OPER 	USBD_REVOKE 	USBD_GRPACC 	USBD_PWD_INTERVAL 	... 	USBD_PPHENV_EXISTS 	USBD_PWD_ALG 	USBD_LEG_PWDHIST_CT 	USBD_XPW_PWDHIST_CT 	USBD_PHR_ALG 	USBD_LEG_PHRHIST_CT 	USBD_XPW_PHRHIST_CT 	USBD_ROAUDIT 	USBD_MFA_FALLBACK 	USBD_PHR_INTERVAL
_NAME 																					
ADCDA 	0200 	ADCDA 	2007-06-01 	IBMUSER 	NO 	NO 	NO 	YES 	NO 	180 	... 	NO 	LEGACY 	000 	000 	NOPHRASE 	000 	000 	NO 	NO 	00000
IBMUSER 	0200 	IBMUSER 	1995-06-06 	IBMUSER 	NO 	YES 	YES 	YES 	NO 	000 	... 	NO 	LEGACY 	000 	000 	NOPHRASE 	000 	000 	NO 	NO 	00000

2 rows × 52 columns

>>> t.users.filter(regex='IBM.*',axis=0)
 	USBD_RECORD_TYPE 	USBD_NAME 	USBD_CREATE_DATE 	USBD_OWNER_ID 	USBD_ADSP 	USBD_SPECIAL 	USBD_OPER 	USBD_REVOKE 	USBD_GRPACC 	USBD_PWD_INTERVAL 	... 	USBD_PPHENV_EXISTS 	USBD_PWD_ALG 	USBD_LEG_PWDHIST_CT 	USBD_XPW_PWDHIST_CT 	USBD_PHR_ALG 	USBD_LEG_PHRHIST_CT 	USBD_XPW_PHRHIST_CT 	USBD_ROAUDIT 	USBD_MFA_FALLBACK 	USBD_PHR_INTERVAL
_NAME 																					
IBMUSCN 	0200 	IBMUSCN 	2019-11-11 	IBMUSER 	NO 	NO 	NO 	NO 	NO 	180 	... 	NO 	NOPASSWORD 	000 	000 	NOPHRASE 	000 	000 	NO 	NO 	00000
IBMUSECN 	0200 	IBMUSECN 	2019-11-11 	IBMUSER 	NO 	NO 	NO 	NO 	NO 	180 	... 	NO 	NOPASSWORD 	000 	000 	NOPHRASE 	000 	000 	NO 	NO 	00000
IBMUSER 	0200 	IBMUSER 	1995-06-06 	IBMUSER 	NO 	YES 	YES 	YES 	NO 	000 	... 	NO 	LEGACY 	000 	000 	NOPHRASE 	000 	000 	NO 	NO 	00000

3 rows × 52 columns
```
There are 3 issues I would like to address:
1. we now have gfilter() and rfilter(), after 1 week not using pyracf, I have to think hard what the method name is, again.  r.users.select('IBM*')..... nope.  We chose gfilter because the name was available, well, a strange looking function name is not always the right choice
2. someone mentioned rfilter reminded him of "RACF filters" and gfilter didn't remind him of generic patterns.
3. it would be great to be able to SELECT and also EXCLUDE records, like so:
``` r.users.gfilter('IBM*').gfilter('NOT', 'IBMUSER') ``` 
or
``` r.users.gfilter('IBM*').gfilter('IBMUSER' ,exclude=True) ```
so we can show all users starting with IBM, except IBMUSER.

I wonder, should be _drop_ gfilter and rfilter, and take a different verb?

a. take it or leave it:
```r.users.take('IBM*').leave('IBMUSER')```
b. leave feels like "leave it in" and "skip" is the opposite of include:
```r.users.take('IBM*').skip('IBMUSER')```
but also
```r.users.skip('IBMUSER')```

The straight-forward use of take and skip should focus on RACF idiom, so it uses generic patterns.  More advanced users might write regex filters, but they would be familiar with Python's r-string type (to take the backslash at face value).
But there is no way for the function to check if the caller entered an r prefix for the string.  And we do not want to force the more advanced user to always start their regex pattern with a ^.
So what it we add an 'r' keyword in these methods that activates regex, like so:

```r.users.take('r', 'IBM.*').skip('IBMUSER')```

or more intuitively for regex connoisseurs force them to enter the program object or package name (basically anything that is not a str:

```r.datasets.take(re, r'SYS\d\..*').skip(re, r'SYS1\.\*\*')```

```r.generals.take(re, 'FACILITY', r'BPX\..*')```

**Comment by wizardofzos** [comment]
Few quick replies from sunny but windy Crete

at first gfilter was 'weird' to be RACF Generic Filter and rfilter for REGEX filter. I do believe those are 'good enough' as they are.... g for generic r for regex.

also I think for 'core' pyRACF it should not be 'too spliffy'.....  From the outset pyracf was meant to give users a panda dataframe per recordtype. I think we fully delivered on that...

The extra functions you made are *reall* nice, cool and handy and have a correct place in pyracf.

Maybe the more 'advanced' tricks should be in a an overarching framework that extends pyracf?

As stated: being able to panda ones way around racf irrbu00 records (with the gfilter, rfilter and acl extensions) is a state I've had envisioned for 1.0.0 o pyracf :)

**Comment by rob-vh** [comment]
Considering that regex users are accomplished programmers and familiar with the re package, why don't we let them compile their patterns explicitly and pass the these as re.Pattern into the selection methods:
```
import re
r.datasets.gfilter( re.compile('SYS1\..*') )
```
where mere RACF admins would have typed `r.datasets.gfilter('SYS1.**')`
Being accomplished python programmers, they might in fact reduce their typing effort:
```
import re
R = re.compile
r.datasets.gfilter( R('SYS1\..*') )
```
So, with this insight we can drop the regex-specific filter function : -)

The new syntax is:
```
r.users.take('IBM*').skip('IBMUSER')   # we know how SEARCH FILTER works

r.users.take( re.compile('IBM.*') ).skip('IBMUSER')  # we know regex better
```

.gfilter and .rfilter can remain for now, with no enhancements or fixes.
