### ISSUE TITLE
UID and GID values are fixed length, 10 character, with leading 0, making it harder to read/use the values

### ISSUE THREAD

**Issue by rob-vh** [wizardofzos/pyracf#41]
The unload file has UID values stored as fixed length, leading zero, numbers:

```
_NAME
ADCDA      0000990008
ADCDB      0000990009
ADCDMST    0000000000
ASH        0000000000
BILLA      0000000100
              ...    
ZOSCAGL    0000009081
ZOSCSRV    0000009082
ZOSMFAD    0000990007
ZOSUGST    0000009080
9735       0000000100
```

This makes it harder to get a list of all users with UID 0, because you have to be careful count the number of characters.

`r.userOMVS.loc[r.userOMVS.USOMVS_UID=='0000000000']`
vs
`r.userOMVS.loc[r.userOMVS.USOMVS_UID=='0']`

We could strip the leading zeros in correlate().  Objections?

**Comment by rob-vh** [comment]
Added publishing routines into ProfilePublisher to assign fields GPOMVS_GID_ and USOMVS_UID_, containing the GID/UID values  with leading zeros stripped.

**Comment by wizardofzos** [comment]
Think better to cast to int ? Sent from my wireless iPhoneOn 8 Jul 2024, at 12:51, rob-vh ***@***.***> wrote:﻿
Added publishing routines into ProfilePublisher to assign fields GPOMVS_GID_ and USOMVS_UID_, containing the GID/UID values  with leading zeros stripped.

**Comment by rob-vh** [comment]
All fields in RACF frames are character now, adding two as int implies we have to start making extra tests for type(field)==str and type(str)==int and specify selection criteria accordingly:

`find(USOMVS_UID_=0) vs. find(USOMVS_UID_='0')`

Also, do you perceive a need to do UID>10000 like tests, which you can still do by referencing the original 10 character field?
